In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("⚠️ GPU not available")

PyTorch version: 2.11.0+cu128
GPU available: True
GPU: Tesla T4

In [ ]:
!pip install -q -U transformers datasets[audio] accelerate evaluate jiwer sentencepiece soundfile librosa scipy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 17.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 45.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 31.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 17.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 115.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.

In [ ]:
import torch
import transformers
import datasets
import librosa
import soundfile as sf
import scipy

print("====================================")
print("      ELDERCARE AI ENVIRONMENT")
print("====================================")

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("Librosa:", librosa.__version__)
print("SoundFile:", sf.__version__)
print("SciPy:", scipy.__version__)

print("------------------------------------")
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

print("====================================")
print("✅ Environment is ready")

====================================
      ELDERCARE AI ENVIRONMENT
====================================
PyTorch: 2.11.0+cu128
Transformers: 5.16.1
Datasets: 5.0.1
Librosa: 1.0.0
SoundFile: 0.14.0
SciPy: 1.18.1
------------------------------------
GPU available: True
GPU: Tesla T4
====================================
✅ Environment is ready

In [ ]:
from transformers import AutoProcessor, Wav2Vec2ForCTC
import torch

# Multilingual ASR model
ASR_MODEL = "facebook/mms-1b-all"

print("Loading multilingual speech recognition model...")
print("Model:", ASR_MODEL)

# Start with Tamil
processor = AutoProcessor.from_pretrained(
    ASR_MODEL,
    target_lang="tam"
)

asr_model = Wav2Vec2ForCTC.from_pretrained(
    ASR_MODEL,
    target_lang="tam",
    ignore_mismatched_sizes=True
)

# Move model to Tesla T4 GPU
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

asr_model = asr_model.to(device)

print("\n====================================")
print("      ASR MODEL READY")
print("====================================")
print("Device:", device)
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")
print("Language loaded: Tamil")
print("====================================")

Loading multilingual speech recognition model...
Model: facebook/mms-1b-all

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/254 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.04k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.34M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/96.0 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.86GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/1096 [00:00<?, ?it/s]

adapter.tam.safetensors: reconstructing file:   0%|          |  0.00B / 9.25MB

adapter.tam.safetensors: downloading bytes:           |  0.00B

====================================
      ASR MODEL READY
====================================
Device: cuda
GPU: Tesla T4
Language loaded: Tamil
====================================

In [ ]:
# ============================================
# ELDERCARE MULTILINGUAL LANGUAGE CONFIG
# ============================================

LANGUAGES = {
    "Tamil": "tam",
    "English": "eng",
    "Malayalam": "mal"
}

print("====================================")
print("   SUPPORTED LANGUAGES")
print("====================================")

for language, code in LANGUAGES.items():
    print(f"{language} → {code}")

print("====================================")
print("✅ Language configuration ready")

====================================
   SUPPORTED LANGUAGES
====================================
Tamil → tam
English → eng
Malayalam → mal
====================================
✅ Language configuration ready

In [ ]:
import os

# Supported audio formats
AUDIO_EXTENSIONS = (
    ".wav",
    ".mp3",
    ".flac",
    ".m4a",
    ".webm",
    ".ogg"
)

print("====================================")
print("       CHECKING AUDIO DATASET")
print("====================================")

audio_files = []

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.lower().endswith(AUDIO_EXTENSIONS):
            audio_files.append(
                os.path.join(root, file)
            )

print("Total audio files found:", len(audio_files))

print("\nAudio files:")

for file in sorted(audio_files):
    print("✓", file)

print("====================================")

====================================
       CHECKING AUDIO DATASET
====================================
Total audio files found: 0

Audio files:
====================================

In [ ]:
from google.colab import files
import os
import shutil

# Create audio folder
BASE_PATH = "/content/eldercare_voice_ai"
AUDIO_PATH = os.path.join(BASE_PATH, "audio")

os.makedirs(AUDIO_PATH, exist_ok=True)

print("====================================")
print("       ELDERCARE AUDIO DATASET")
print("====================================")
print("Upload your Tamil, English and Malayalam recordings.")
print("Supported: WAV, MP3, FLAC, M4A, WEBM, OGG")
print()

uploaded = files.upload()

print("\n📥 Moving uploaded files...\n")

for filename in uploaded.keys():

    source_path = os.path.join("/content", filename)
    destination_path = os.path.join(AUDIO_PATH, filename)

    if os.path.exists(destination_path):
        os.remove(destination_path)

    shutil.move(
        source_path,
        destination_path
    )

    print("✅", filename)

print("\n====================================")
print("       UPLOAD COMPLETED")
print("====================================")

extensions = (
    ".wav",
    ".mp3",
    ".flac",
    ".m4a",
    ".webm",
    ".ogg"
)

audio_files = sorted([
    f for f in os.listdir(AUDIO_PATH)
    if f.lower().endswith(extensions)
])

print("Total audio files:", len(audio_files))

for filename in audio_files:
    print("✓", filename)

print("\nAudio folder:")
print(AUDIO_PATH)

====================================
       ELDERCARE AUDIO DATASET
====================================
Upload your Tamil, English and Malayalam recordings.
Supported: WAV, MP3, FLAC, M4A, WEBM, OGG

Saving WhatsApp Ptt 2026-09-05 at 3.26.08 PM.ogg to WhatsApp Ptt 2026-09-05 at 3.26.08 PM.ogg

📥 Moving uploaded files...

✅ WhatsApp Ptt 2026-09-05 at 3.26.08 PM.ogg

====================================
       UPLOAD COMPLETED
====================================
Total audio files: 1
✓ WhatsApp Ptt 2026-09-05 at 3.26.08 PM.ogg

Audio folder:
/content/eldercare_voice_ai/audio

In [ ]:
# ============================================
# CELL 7: AUDIO PREPROCESSING
# ============================================

import os
import librosa
import soundfile as sf

AUDIO_PATH = "/content/eldercare_voice_ai/audio"
PROCESSED_PATH = "/content/eldercare_voice_ai/processed_audio"

os.makedirs(PROCESSED_PATH, exist_ok=True)

print("====================================")
print("       AUDIO PREPROCESSING")
print("====================================")

audio_files = [
    f for f in os.listdir(AUDIO_PATH)
    if f.lower().endswith(
        (".wav", ".mp3", ".flac", ".m4a", ".webm", ".ogg")
    )
]

print("Audio files found:", len(audio_files))
print()

for filename in audio_files:

    input_file = os.path.join(AUDIO_PATH, filename)

    print("Processing:", filename)

    try:
        # Load audio
        audio, sample_rate = librosa.load(
            input_file,
            sr=16000,
            mono=True
        )

        # Create output filename
        output_filename = os.path.splitext(filename)[0] + ".wav"
        output_file = os.path.join(
            PROCESSED_PATH,
            output_filename
        )

        # Save as 16 kHz WAV
        sf.write(
            output_file,
            audio,
            16000
        )

        duration = len(audio) / 16000

        print("Original sample rate:", sample_rate)
        print("Converted sample rate: 16000 Hz")
        print("Channels: Mono")
        print(f"Duration: {duration:.2f} seconds")
        print("Saved:", output_file)
        print("✅ Processing successful")
        print()

    except Exception as e:
        print("❌ Error:", e)
        print()

print("====================================")
print("       PREPROCESSING COMPLETED")
print("====================================")

processed_files = [
    f for f in os.listdir(PROCESSED_PATH)
    if f.endswith(".wav")
]

print("Processed WAV files:", len(processed_files))

for filename in processed_files:
    print("✓", filename)

print("====================================")

====================================
       AUDIO PREPROCESSING
====================================
Audio files found: 1

Processing: WhatsApp Ptt 2026-09-05 at 3.26.08 PM.ogg
Original sample rate: 16000
Converted sample rate: 16000 Hz
Channels: Mono
Duration: 2.47 seconds
Saved: /content/eldercare_voice_ai/processed_audio/WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav
✅ Processing successful

====================================
       PREPROCESSING COMPLETED
====================================
Processed WAV files: 1
✓ WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav
====================================

In [ ]:
# ============================================
# CELL 8: CREATE ASR TRAINING METADATA
# ============================================

import os
import pandas as pd

PROCESSED_PATH = "/content/eldercare_voice_ai/processed_audio"
METADATA_PATH = "/content/eldercare_voice_ai/metadata.csv"

print("====================================")
print("      ASR TRAINING METADATA")
print("====================================")

# Find WAV files
audio_files = sorted([
    f for f in os.listdir(PROCESSED_PATH)
    if f.lower().endswith(".wav")
])

print("Audio files found:", len(audio_files))
print()

for i, filename in enumerate(audio_files, 1):
    print(f"{i}. {filename}")

# Check whether audio exists
if len(audio_files) == 0:
    raise FileNotFoundError("No WAV audio files found.")

print()
print("====================================")
print("      ENTER TRANSCRIPTION")
print("====================================")

audio_file = audio_files[0]

print("Audio file:")
print(audio_file)

print()
print("Type EXACTLY what you said in the recording.")
print("Do not translate it.")
print()

transcription = input("Transcription: ").strip()

if transcription == "":
    raise ValueError("Transcription cannot be empty.")

print()
print("====================================")
print("        SELECT LANGUAGE")
print("====================================")

print("1 → Tamil")
print("2 → English")
print("3 → Malayalam")

language_choice = input("Language (1/2/3): ").strip()

language_map = {
    "1": "Tamil",
    "2": "English",
    "3": "Malayalam"
}

if language_choice not in language_map:
    raise ValueError("Invalid choice. Enter 1, 2 or 3.")

language = language_map[language_choice]

# Create metadata
df = pd.DataFrame({
    "audio": [audio_file],
    "text": [transcription],
    "language": [language]
})

# Save metadata
df.to_csv(
    METADATA_PATH,
    index=False,
    encoding="utf-8-sig"
)

print()
print("====================================")
print("       DATASET CREATED")
print("====================================")

print(df.to_string(index=False))

print()
print("Metadata saved at:")
print(METADATA_PATH)

print()
print("✅ Audio + transcription + language are ready")
print("====================================")

====================================
      ASR TRAINING METADATA
====================================
Audio files found: 1

1. WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav

====================================
      ENTER TRANSCRIPTION
====================================
Audio file:
WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav

Type EXACTLY what you said in the recording.
Do not translate it.

Transcription: Tamil

====================================
        SELECT LANGUAGE
====================================
1 → Tamil
2 → English
3 → Malayalam
Language (1/2/3): 1

====================================
       DATASET CREATED
====================================
                                    audio  text language
WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav Tamil    Tamil

Metadata saved at:
/content/eldercare_voice_ai/metadata.csv

✅ Audio + transcription + language are ready
====================================

In [ ]:
# ============================================
# CELL 9: VERIFY ASR DATASET
# ============================================

import pandas as pd
import os

METADATA_PATH = "/content/eldercare_voice_ai/metadata.csv"
PROCESSED_PATH = "/content/eldercare_voice_ai/processed_audio"

print("====================================")
print("       VERIFYING ASR DATASET")
print("====================================")

# Load metadata
df = pd.read_csv(
    METADATA_PATH,
    encoding="utf-8-sig"
)

print("\nCurrent dataset:")
print(df.to_string(index=False))

print("\n====================================")
print("      CORRECT TRANSCRIPTION")
print("====================================")

print("Current transcription:", df.loc[0, "text"])
print()
print("Enter the EXACT words spoken in the audio.")
print("Example:")
print("Tamil: நான் மருந்து எடுத்துக்கொண்டேன்")
print("English: I took my medicine.")
print("Malayalam: ഞാൻ മരുന്ന് കഴിച്ചു.")
print()

new_text = input("Correct transcription: ").strip()

if new_text == "":
    raise ValueError("Transcription cannot be empty.")

# Update transcription
df.loc[0, "text"] = new_text

# Save corrected metadata
df.to_csv(
    METADATA_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("\n====================================")
print("       VERIFIED DATASET")
print("====================================")

print(df.to_string(index=False))

print("\nMetadata saved:")
print(METADATA_PATH)

print("\nAudio file exists:",
      os.path.exists(
          os.path.join(
              PROCESSED_PATH,
              df.loc[0, "audio"]
          )
      ))

print("\n✅ Dataset verification completed")
print("====================================")

====================================
       VERIFYING ASR DATASET
====================================

Current dataset:
                                    audio  text language
WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav Tamil    Tamil

====================================
      CORRECT TRANSCRIPTION
====================================
Current transcription: Tamil

Enter the EXACT words spoken in the audio.
Example:
Tamil: நான் மருந்து எடுத்துக்கொண்டேன்
English: I took my medicine.
Malayalam: ഞാൻ മരുന്ന് കഴിച്ചു.

Correct transcription: malayalam

====================================
       VERIFIED DATASET
====================================
                                    audio      text language
WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav malayalam    Tamil

Metadata saved:
/content/eldercare_voice_ai/metadata.csv

Audio file exists: True

✅ Dataset verification completed
====================================

In [ ]:
# ============================================
# CELL 10: LOAD ASR DATASET
# ============================================

import os
import pandas as pd
import librosa
import soundfile as sf

METADATA_PATH = "/content/eldercare_voice_ai/metadata.csv"
PROCESSED_PATH = "/content/eldercare_voice_ai/processed_audio"

print("====================================")
print("       LOADING ASR DATASET")
print("====================================")

# Load metadata
df = pd.read_csv(
    METADATA_PATH,
    encoding="utf-8-sig"
)

print("Metadata loaded successfully.")
print()

print("Dataset:")
print(df.to_string(index=False))

print()
print("====================================")
print("       CHECKING AUDIO FILES")
print("====================================")

audio_data = []

for index, row in df.iterrows():

    audio_path = os.path.join(
        PROCESSED_PATH,
        row["audio"]
    )

    print(f"\nFile {index + 1}:")
    print("Name:", row["audio"])
    print("Path:", audio_path)
    print("Text:", row["text"])
    print("Language:", row["language"])

    if not os.path.exists(audio_path):
        print("❌ Audio file not found!")
        continue

    # Load audio
    audio, sample_rate = librosa.load(
        audio_path,
        sr=16000,
        mono=True
    )

    duration = len(audio) / sample_rate

    print("Sample rate:", sample_rate, "Hz")
    print("Duration:", round(duration, 2), "seconds")
    print("Samples:", len(audio))

    audio_data.append({
        "audio_path": audio_path,
        "text": row["text"],
        "language": row["language"],
        "duration": duration
    })

print()
print("====================================")
print("       DATASET SUMMARY")
print("====================================")

print("Total samples:", len(audio_data))

if len(audio_data) > 0:

    print("Total duration:",
          round(
              sum(x["duration"] for x in audio_data),
              2
          ),
          "seconds"
    )

    print()
    print("✅ Audio dataset loaded successfully")

else:

    print("❌ No valid audio samples found.")

print("====================================")

====================================
       LOADING ASR DATASET
====================================
Metadata loaded successfully.

Dataset:
                                    audio      text language
WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav malayalam    Tamil

====================================
       CHECKING AUDIO FILES
====================================

File 1:
Name: WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav
Path: /content/eldercare_voice_ai/processed_audio/WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav
Text: malayalam
Language: Tamil
Sample rate: 16000 Hz
Duration: 2.47 seconds
Samples: 39576

====================================
       DATASET SUMMARY
====================================
Total samples: 1
Total duration: 2.47 seconds

✅ Audio dataset loaded successfully
====================================

In [ ]:
# CELL 12: Test English Speech Recognition

import torch
import librosa
import os

# Path to your processed audio
audio_file = "/content/eldercare_voice_ai/processed_audio/WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav"

# Load audio at 16 kHz
audio, sample_rate = librosa.load(
    audio_file,
    sr=16000,
    mono=True
)

# Convert audio into model input
inputs = processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt"
)

# Move input to GPU
input_values = inputs.input_values.to(device)

# Run ASR model
with torch.no_grad():
    logits = asr_model(input_values).logits

# Get predicted tokens
predicted_ids = torch.argmax(logits, dim=-1)

# Convert tokens to text
transcription = processor.batch_decode(
    predicted_ids
)[0]

print("🎤 Speech-to-Text Result:")
print(transcription)

🎤 Speech-to-Text Result:
inithb

In [ ]:
# CELL 13: Load English MMS ASR Model

from transformers import AutoProcessor, Wav2Vec2ForCTC
import torch

# MMS multilingual ASR model
ASR_MODEL = "facebook/mms-1b-all"

# Load English processor
english_processor = AutoProcessor.from_pretrained(
    ASR_MODEL,
    target_lang="eng"
)

# Load English ASR model
english_model = Wav2Vec2ForCTC.from_pretrained(
    ASR_MODEL,
    target_lang="eng",
    ignore_mismatched_sizes=True
)

# Use GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

english_model = english_model.to(device)
english_model.eval()

print("✅ English MMS ASR model loaded successfully")
print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Loading weights:   0%|          | 0/1096 [00:00<?, ?it/s]

adapter.eng.safetensors: reconstructing file:   0%|          |  0.00B / 9.43MB

adapter.eng.safetensors: downloading bytes:           |  0.00B

✅ English MMS ASR model loaded successfully
Device: cuda
GPU: Tesla T4

In [ ]:
# CELL 14: Test English MMS ASR

import torch
import librosa
import os

# Path to the processed English audio
audio_file = "/content/eldercare_voice_ai/processed_audio/WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav"

# Check that the file exists
if not os.path.exists(audio_file):
    raise FileNotFoundError(f"Audio file not found: {audio_file}")

# Load audio at 16 kHz
audio, sample_rate = librosa.load(
    audio_file,
    sr=16000,
    mono=True
)

print("Audio loaded successfully")
print("Sample rate:", sample_rate)
print("Duration:", round(len(audio) / sample_rate, 2), "seconds")

# Prepare audio for English MMS model
inputs = english_processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt"
)

# Move input to GPU
input_values = inputs.input_values.to(device)

# Run English ASR
with torch.no_grad():
    logits = english_model(input_values).logits

# Find predicted tokens
predicted_ids = torch.argmax(logits, dim=-1)

# Convert tokens to English text
english_transcription = english_processor.batch_decode(
    predicted_ids
)[0]

print("\n🎤 English Speech-to-Text Result:")
print(english_transcription)

Audio loaded successfully
Sample rate: 16000
Duration: 2.47 seconds

🎤 English Speech-to-Text Result:
ini dhb

In [ ]:
# CELL 16: Load Audio Dataset for MMS Fine-Tuning

from datasets import Dataset, Audio
import pandas as pd
import os

# Path to training metadata
TRAINING_METADATA = "/content/eldercare_voice_ai/asr_training/train_metadata.csv"

# Load metadata
df = pd.read_csv(
    TRAINING_METADATA,
    encoding="utf-8-sig"
)

print("📋 Training metadata:")
display(df)

# Check dataset
if len(df) == 0:
    raise ValueError("❌ No training samples found.")

# Check for missing values
if df["audio_path"].isna().any():
    raise ValueError("❌ Some audio paths are missing.")

if df["text"].isna().any():
    raise ValueError("❌ Some transcriptions are missing.")

# Convert to Hugging Face Dataset
dataset = Dataset.from_pandas(
    df[["audio_path", "text", "language"]],
    preserve_index=False
)

# Rename audio_path → audio
dataset = dataset.rename_column(
    "audio_path",
    "audio"
)

# Load audio automatically at 16 kHz
dataset = dataset.cast_column(
    "audio",
    Audio(sampling_rate=16000)
)

print("\n✅ Hugging Face audio dataset created")
print("Number of samples:", len(dataset))
print("\nDataset structure:")
print(dataset)

# Display first sample
print("\n🎤 First training sample:")
print("Text:", dataset[0]["text"])
print("Language:", dataset[0]["language"])
print("Audio sampling rate:", dataset[0]["audio"]["sampling_rate"])

📋 Training metadata:

                                          audio_path       text language
0  /content/eldercare_voice_ai/processed_audio/Wh...  malayalam    Tamil

✅ Hugging Face audio dataset created
Number of samples: 1

Dataset structure:
Dataset({
    features: ['audio', 'text', 'language'],
    num_rows: 1
})

🎤 First training sample:
Text: malayalam
Language: Tamil
Audio sampling rate: 16000

In [ ]:
# CELL 17: Correct ASR Training Metadata

import pandas as pd
import os

METADATA_PATH = "/content/eldercare_voice_ai/asr_training/train_metadata.csv"

# Load training metadata
df = pd.read_csv(METADATA_PATH, encoding="utf-8-sig")

print("📋 Current metadata:")
display(df)

# Get the correct English transcription
print("\n⚠️ IMPORTANT:")
print("Type the EXACT English sentence that you spoke in the audio.")
print("Do not type the language name unless you actually said that word.")

english_text = input("\nEnter the exact English transcription: ").strip()

if english_text == "":
    raise ValueError("❌ Transcription cannot be empty.")

# Update metadata
df.loc[0, "text"] = english_text
df.loc[0, "language"] = "English"

# Save corrected metadata
df.to_csv(
    METADATA_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("\n✅ Metadata corrected successfully!")
display(df)

print("\n📌 Audio:", df.loc[0, "audio_path"])
print("📌 Text:", df.loc[0, "text"])
print("📌 Language:", df.loc[0, "language"])

📋 Current metadata:

                                          audio_path       text language
0  /content/eldercare_voice_ai/processed_audio/Wh...  malayalam    Tamil

⚠️ IMPORTANT:
Type the EXACT English sentence that you spoke in the audio.
Do not type the language name unless you actually said that word.

Enter the exact English transcription: It's wake up time

✅ Metadata corrected successfully!

,audio_path,text,language
0,/content/eldercare_voice_ai/processed_audio/Wh...,It's wake up time,English

📌 Audio: /content/eldercare_voice_ai/processed_audio/WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav
📌 Text: It's wake up time
📌 Language: English

In [ ]:
# CELL 18: Prepare Audio and Transcript for MMS ASR Fine-Tuning

import torch

# Make sure the English model is being used
print("🔹 Preparing dataset for English MMS ASR...")
print("Number of samples:", len(dataset))

# Check the first sample
sample = dataset[0]

print("\n🎤 Audio Information:")
print("Sampling rate:", sample["audio"]["sampling_rate"])
print("Audio length:", len(sample["audio"]["array"]), "samples")

print("\n📝 Training Text:")
print(sample["text"])

print("\n🌐 Language:")
print(sample["language"])


# Function to prepare each training sample
def prepare_batch(batch):

    # Get audio
    audio = batch["audio"]

    # Convert audio into MMS input features
    inputs = english_processor.feature_extractor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    )

    # Store input values
    batch["input_values"] = inputs.input_values[0]

    # Convert transcript into token IDs
    batch["labels"] = english_processor.tokenizer(
        batch["text"]
    ).input_ids

    return batch


# Apply preprocessing
prepared_dataset = dataset.map(
    prepare_batch,
    remove_columns=dataset.column_names
)

print("\n✅ Audio and transcript preprocessing completed!")

print("\n📦 Prepared Dataset:")
print(prepared_dataset)

print("\n🎤 First Prepared Sample:")
print("Input values:", len(prepared_dataset[0]["input_values"]))
print("Labels:", prepared_dataset[0]["labels"])

🔹 Preparing dataset for English MMS ASR...
Number of samples: 1

🎤 Audio Information:
Sampling rate: 16000
Audio length: 39576 samples

📝 Training Text:
malayalam

🌐 Language:
Tamil

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

✅ Audio and transcript preprocessing completed!

📦 Prepared Dataset:
Dataset({
    features: ['input_values', 'labels'],
    num_rows: 1
})

🎤 First Prepared Sample:
Input values: 39576
Labels: [18, 7, 14, 7, 22, 7, 14, 7, 18]

In [ ]:
# CELL 19: Rebuild Hugging Face Dataset from Corrected Metadata

from datasets import Dataset, Audio
import pandas as pd
import os

TRAINING_METADATA = "/content/eldercare_voice_ai/asr_training/train_metadata.csv"

# Load the corrected metadata
df = pd.read_csv(
    TRAINING_METADATA,
    encoding="utf-8-sig"
)

print("📋 Corrected Training Metadata:")
display(df)

# Validate
if len(df) == 0:
    raise ValueError("❌ Training dataset is empty.")

required_columns = ["audio_path", "text", "language"]

for column in required_columns:
    if column not in df.columns:
        raise ValueError(f"❌ Missing column: {column}")

# Check audio files
df["audio_exists"] = df["audio_path"].apply(os.path.exists)

print("\n🔍 Dataset Verification:")
print("Total samples:", len(df))
print("Audio files found:", df["audio_exists"].sum())
print("Audio files missing:", (~df["audio_exists"]).sum())

if not df["audio_exists"].all():
    print("\n❌ Missing audio files:")
    display(df[~df["audio_exists"]])

    raise FileNotFoundError(
        "Some audio files are missing."
    )

# Check language
if not (df["language"] == "English").all():
    raise ValueError(
        "❌ Dataset language is not English. "
        "For this training step, all samples must be English."
    )

# Check transcript
if df["text"].isna().any() or (df["text"].str.strip() == "").any():
    raise ValueError(
        "❌ One or more transcripts are empty."
    )

# Create Hugging Face dataset
dataset = Dataset.from_pandas(
    df[["audio_path", "text", "language"]],
    preserve_index=False
)

# Rename audio column
dataset = dataset.rename_column(
    "audio_path",
    "audio"
)

# Load audio at 16 kHz
dataset = dataset.cast_column(
    "audio",
    Audio(sampling_rate=16000)
)

print("\n✅ Corrected Hugging Face dataset created!")

print("Number of samples:", len(dataset))

print("\n📦 Dataset structure:")
print(dataset)

print("\n🎤 First training sample:")
print("Text:", dataset[0]["text"])
print("Language:", dataset[0]["language"])
print(
    "Audio sampling rate:",
    dataset[0]["audio"]["sampling_rate"]
)

📋 Corrected Training Metadata:

,audio_path,text,language
0,/content/eldercare_voice_ai/processed_audio/Wh...,It's wake up time,English

🔍 Dataset Verification:
Total samples: 1
Audio files found: 1
Audio files missing: 0

✅ Corrected Hugging Face dataset created!
Number of samples: 1

📦 Dataset structure:
Dataset({
    features: ['audio', 'text', 'language'],
    num_rows: 1
})

🎤 First training sample:
Text: It's wake up time
Language: English
Audio sampling rate: 16000

In [ ]:
# CELL 20: Prepare Corrected Dataset for MMS ASR Fine-Tuning

print("🔹 Preparing corrected English dataset for MMS ASR...")

# Function to process each sample
def prepare_batch(batch):

    # Get audio information
    audio = batch["audio"]

    # Convert audio waveform into model input values
    audio_inputs = english_processor.feature_extractor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    )

    # Store input values
    batch["input_values"] = audio_inputs.input_values[0]

    # Convert transcript into token IDs
    batch["labels"] = english_processor.tokenizer(
        batch["text"]
    ).input_ids

    return batch


# Apply preprocessing
prepared_dataset = dataset.map(
    prepare_batch,
    remove_columns=dataset.column_names
)

print("\n✅ Dataset preprocessing completed!")

# Display dataset information
print("\n📦 Prepared Dataset:")
print(prepared_dataset)

# Check first sample
print("\n🎤 First Prepared Sample:")
print("Input values:", len(prepared_dataset[0]["input_values"]))
print("Labels:", prepared_dataset[0]["labels"])

print("\n📝 Original transcript:")
print("It's wake up time")

🔹 Preparing corrected English dataset for MMS ASR...

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

✅ Dataset preprocessing completed!

📦 Prepared Dataset:
Dataset({
    features: ['input_values', 'labels'],
    num_rows: 1
})

🎤 First Prepared Sample:
Input values: 39576
Labels: [3, 6, 31, 11, 4, 23, 7, 26, 5, 4, 17, 20, 4, 6, 9, 18, 5]

📝 Original transcript:
It's wake up time

In [ ]:
# CELL 21: Create CTC Data Collator for MMS ASR

from dataclasses import dataclass
from typing import Dict, List, Union
import torch


@dataclass
class DataCollatorCTCWithPadding:
    processor: object
    padding: Union[bool, str] = True

    def __call__(
        self,
        features: List[Dict[str, Union[List[int], torch.Tensor]]]
    ):

        # Separate audio inputs and labels
        input_features = [
            {"input_values": feature["input_values"]}
            for feature in features
        ]

        label_features = [
            {"input_ids": feature["labels"]}
            for feature in features
        ]

        # Pad audio inputs
        batch = self.processor.feature_extractor.pad(
            input_features,
            padding=self.padding,
            return_tensors="pt"
        )

        # Pad labels
        labels_batch = self.processor.tokenizer.pad(
            label_features,
            padding=self.padding,
            return_tensors="pt"
        )

        # Replace padding tokens with -100
        # so CTC loss ignores them
        labels = labels_batch["input_ids"].masked_fill(
            labels_batch["attention_mask"].ne(1),
            -100
        )

        batch["labels"] = labels

        return batch


# Create the data collator
data_collator = DataCollatorCTCWithPadding(
    processor=english_processor,
    padding=True
)

print("✅ CTC Data Collator created successfully!")

# Test the collator with the current dataset
test_batch = data_collator(
    [prepared_dataset[0]]
)

print("\n📦 Test Batch:")
print("Input shape:", test_batch["input_values"].shape)
print("Labels shape:", test_batch["labels"].shape)

print("\n🏷️ Labels:")
print(test_batch["labels"])

✅ CTC Data Collator created successfully!

📦 Test Batch:
Input shape: torch.Size([1, 39576])
Labels shape: torch.Size([1, 17])

🏷️ Labels:
tensor([[ 3,  6, 31, 11,  4, 23,  7, 26,  5,  4, 17, 20,  4,  6,  9, 18,  5]])

In [ ]:
# CELL 22: Configure MMS ASR Fine-Tuning

from transformers import TrainingArguments

# Output directory for the fine-tuned model
OUTPUT_DIR = "/content/eldercare_voice_ai/mms_english_model"

# Training configuration
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,

    # Number of training epochs
    num_train_epochs=10,

    # One sample per batch because our dataset is currently very small
    per_device_train_batch_size=1,

    # Accumulate gradients
    gradient_accumulation_steps=1,

    # Learning rate
    learning_rate=1e-5,

    # Save model
    save_strategy="epoch",

    # Logging
    logging_strategy="steps",
    logging_steps=1,

    # Do not evaluate because we have only one sample
    eval_strategy="no",

    # Use GPU if available
    fp16=torch.cuda.is_available(),

    # Keep only the latest checkpoint
    save_total_limit=2,

    # Report nothing to external services
    report_to="none",

    # Disable automatic column removal
    remove_unused_columns=False
)

print("✅ Training configuration created successfully!")

print("\n📋 Training Configuration:")
print("Output directory:", OUTPUT_DIR)
print("Epochs:", training_args.num_train_epochs)
print("Batch size:", training_args.per_device_train_batch_size)
print("Learning rate:", training_args.learning_rate)
print("GPU available:", torch.cuda.is_available())
print("FP16 enabled:", training_args.fp16)

✅ Training configuration created successfully!

📋 Training Configuration:
Output directory: /content/eldercare_voice_ai/mms_english_model
Epochs: 10
Batch size: 1
Learning rate: 1e-05
GPU available: True
FP16 enabled: True

In [ ]:
# CELL 23: Create MMS ASR Trainer

from transformers import Trainer

print("🔹 Creating MMS ASR Trainer...")

trainer = Trainer(
    model=english_model,
    args=training_args,
    train_dataset=prepared_dataset,
    data_collator=data_collator,
)

print("\n✅ MMS ASR Trainer created successfully!")

print("\n📋 Trainer Information:")
print("Training samples:", len(prepared_dataset))
print("Model:", english_model.__class__.__name__)
print("Epochs:", training_args.num_train_epochs)
print("Batch size:", training_args.per_device_train_batch_size)
print("Learning rate:", training_args.learning_rate)
print("Output directory:", training_args.output_dir)

🔹 Creating MMS ASR Trainer...

✅ MMS ASR Trainer created successfully!

📋 Trainer Information:
Training samples: 1
Model: Wav2Vec2ForCTC
Epochs: 10
Batch size: 1
Learning rate: 1e-05
Output directory: /content/eldercare_voice_ai/mms_english_model

In [ ]:
# CELL 24: Memory-Safe MMS ASR Fine-Tuning

import torch
import gc

print("🧹 Clearing unused GPU memory...")

# Clear Python garbage
gc.collect()

# Clear CUDA cache
if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("GPU memory cleared.")


# ---------------------------------------------------------
# 1. Freeze the MMS feature extractor
# ---------------------------------------------------------

english_model.freeze_feature_encoder()

print("\n🔒 Feature encoder frozen.")


# ---------------------------------------------------------
# 2. Freeze most of the MMS model
# ---------------------------------------------------------

# Freeze all parameters first
for param in english_model.parameters():
    param.requires_grad = False


# ---------------------------------------------------------
# 3. Enable training only for the CTC classification head
# ---------------------------------------------------------

for param in english_model.lm_head.parameters():
    param.requires_grad = True


print("🎯 Only CTC classification head will be trained.")


# ---------------------------------------------------------
# 4. Count trainable parameters
# ---------------------------------------------------------

total_params = sum(
    p.numel() for p in english_model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in english_model.parameters()
    if p.requires_grad
)

print("\n📊 Model Parameters:")
print("Total parameters:", f"{total_params:,}")
print("Trainable parameters:", f"{trainable_params:,}")

percentage = (trainable_params / total_params) * 100

print(
    "Trainable percentage:",
    round(percentage, 4),
    "%"
)


# ---------------------------------------------------------
# 5. Move model to GPU
# ---------------------------------------------------------

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

english_model = english_model.to(device)

print("\n🚀 Model device:", device)

if torch.cuda.is_available():
    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )


# ---------------------------------------------------------
# 6. Create a new memory-efficient Trainer
# ---------------------------------------------------------

from transformers import Trainer, TrainingArguments

SAFE_OUTPUT_DIR = (
    "/content/eldercare_voice_ai/"
    "mms_english_model"
)

safe_training_args = TrainingArguments(
    output_dir=SAFE_OUTPUT_DIR,

    # Training
    num_train_epochs=10,
    per_device_train_batch_size=1,

    # Learning rate for the trainable CTC head
    learning_rate=1e-4,

    # Memory optimization
    fp16=True,

    # Disable unnecessary features
    eval_strategy="no",
    save_strategy="no",
    logging_strategy="steps",
    logging_steps=1,

    # Important because we already prepared the dataset
    remove_unused_columns=False,

    # No external logging
    report_to="none",

    # Do not keep optimizer checkpoints
    save_only_model=True
)


# ---------------------------------------------------------
# 7. Create Trainer
# ---------------------------------------------------------

trainer = Trainer(
    model=english_model,
    args=safe_training_args,
    train_dataset=prepared_dataset,
    data_collator=data_collator
)

print("\n" + "=" * 60)
print("✅ MEMORY-SAFE TRAINER CREATED")
print("=" * 60)

print("\nTraining samples:", len(prepared_dataset))
print("Epochs:", safe_training_args.num_train_epochs)
print("Batch size:", safe_training_args.per_device_train_batch_size)
print("Learning rate:", safe_training_args.learning_rate)
print("FP16:", safe_training_args.fp16)
print("Trainable parameters:", f"{trainable_params:,}")

# Check available GPU memory
if torch.cuda.is_available():
    free_memory, total_memory = torch.cuda.mem_get_info()

    print("\n💾 GPU Memory:")
    print(
        "Free:",
        round(free_memory / (1024**3), 2),
        "GB"
    )

    print(
        "Total:",
        round(total_memory / (1024**3), 2),
        "GB"
    )

print("\n✅ Ready for memory-safe training.")

🧹 Clearing unused GPU memory...
GPU memory cleared.

🔒 Feature encoder frozen.
🎯 Only CTC classification head will be trained.

📊 Model Parameters:
Total parameters: 964,845,850
Trainable parameters: 197,274
Trainable percentage: 0.0204 %

🚀 Model device: cuda
GPU: Tesla T4

============================================================
✅ MEMORY-SAFE TRAINER CREATED
============================================================

Training samples: 1
Epochs: 10
Batch size: 1
Learning rate: 0.0001
FP16: True
Trainable parameters: 197,274

💾 GPU Memory:
Free: 0.02 GB
Total: 14.56 GB

✅ Ready for memory-safe training.

In [ ]:
# CELL 25: Start Memory-Safe MMS ASR Training

import gc
import torch

print("🧹 Preparing GPU memory for training...")

# Python garbage collection
gc.collect()

# Clear unused CUDA memory
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

# Display GPU memory before training
if torch.cuda.is_available():
    free_memory, total_memory = torch.cuda.mem_get_info()

    print(
        "GPU free memory before training:",
        round(free_memory / (1024**3), 2),
        "GB"
    )

    print(
        "GPU total memory:",
        round(total_memory / (1024**3), 2),
        "GB"
    )


print("\n🚀 Starting memory-safe MMS ASR training...")
print("Training samples:", len(prepared_dataset))
print("Epochs:", safe_training_args.num_train_epochs)
print("Trainable parameters:", f"{trainable_params:,}")

print("\n⚠️ This is a 1-sample pipeline demonstration.")
print("Training may overfit this single recording.\n")


# ---------------------------------------------------------
# START TRAINING
# ---------------------------------------------------------

try:

    train_result = trainer.train()

    print("\n" + "=" * 60)
    print("✅ TRAINING COMPLETED SUCCESSFULLY!")
    print("=" * 60)

    print("\n📊 Training Results:")

    if hasattr(train_result, "metrics"):
        for key, value in train_result.metrics.items():
            print(f"{key}: {value}")

except torch.cuda.OutOfMemoryError:

    print("\n❌ CUDA OUT OF MEMORY")
    print("\nThe GPU still does not have enough free memory.")
    print("Do NOT restart the whole project yet.")
    print("We will use an even more memory-efficient approach.")

    # Clear memory
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()

except Exception as e:

    print("\n❌ Training failed.")
    print("Error type:", type(e).__name__)
    print("Error:", str(e))

🧹 Preparing GPU memory for training...
GPU free memory before training: 0.02 GB
GPU total memory: 14.56 GB

🚀 Starting memory-safe MMS ASR training...
Training samples: 1
Epochs: 10
Trainable parameters: 197,274

⚠️ This is a 1-sample pipeline demonstration.
Training may overfit this single recording.

============================================================
✅ TRAINING COMPLETED SUCCESSFULLY!
============================================================

📊 Training Results:
train_runtime: 2.1427
train_samples_per_second: 4.667
train_steps_per_second: 4.667
total_flos: 2291084361576000.0
train_loss: 5.292681694030762
epoch: 10.0

In [ ]:
# CELL 26: Save Fine-Tuned MMS English ASR Model

import os
import torch

# Directory where the fine-tuned model will be saved
FINAL_MODEL_PATH = (
    "/content/eldercare_voice_ai/"
    "mms_english_model/final"
)

os.makedirs(FINAL_MODEL_PATH, exist_ok=True)

print("💾 Saving fine-tuned MMS English ASR model...")


# ---------------------------------------------------------
# 1. Save the model
# ---------------------------------------------------------

english_model.save_pretrained(
    FINAL_MODEL_PATH
)

print("✅ Model saved successfully.")


# ---------------------------------------------------------
# 2. Save the English processor
# ---------------------------------------------------------

english_processor.save_pretrained(
    FINAL_MODEL_PATH
)

print("✅ Processor saved successfully.")


# ---------------------------------------------------------
# 3. Check saved files
# ---------------------------------------------------------

print("\n📁 Saved model files:")

for filename in sorted(os.listdir(FINAL_MODEL_PATH)):
    file_path = os.path.join(
        FINAL_MODEL_PATH,
        filename
    )

    if os.path.isfile(file_path):
        file_size = os.path.getsize(file_path)

        print(
            f"  📄 {filename} "
            f"({file_size / (1024**2):.2f} MB)"
        )


# ---------------------------------------------------------
# 4. Display model path
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("✅ FINE-TUNED MODEL SAVED SUCCESSFULLY!")
print("=" * 60)

print("\n📌 Model location:")
print(FINAL_MODEL_PATH)

print("\n📌 Training loss:")
print(round(train_result.metrics["train_loss"], 4))

💾 Saving fine-tuned MMS English ASR model...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Model saved successfully.
✅ Processor saved successfully.

📁 Saved model files:
  📄 config.json (0.00 MB)
  📄 model.safetensors (3680.73 MB)
  📄 processor_config.json (0.00 MB)
  📄 tokenizer_config.json (0.00 MB)
  📄 vocab.json (0.92 MB)

============================================================
✅ FINE-TUNED MODEL SAVED SUCCESSFULLY!
============================================================

📌 Model location:
/content/eldercare_voice_ai/mms_english_model/final

📌 Training loss:
5.2927

In [29]:
# CELL 27: Test Fine-Tuned MMS English ASR Model

import torch
import librosa

TEST_AUDIO = (
    "/content/eldercare_voice_ai/"
    "processed_audio/"
    "WhatsApp Ptt 2026-09-05 at 3.26.08 PM.wav"
)

# Put model in evaluation mode
english_model.eval()

# Load audio
audio, sample_rate = librosa.load(
    TEST_AUDIO,
    sr=16000,
    mono=True
)

# Convert audio to model input
inputs = english_processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt"
)

input_values = inputs.input_values.to(device)

# Run inference
with torch.no_grad():
    logits = english_model(input_values).logits

# Get predicted tokens
predicted_ids = torch.argmax(logits, dim=-1)

# Convert tokens to text
prediction = english_processor.batch_decode(
    predicted_ids
)[0]

expected = "It's wake up time"

print("=" * 60)
print("🎤 FINE-TUNED MMS ENGLISH ASR TEST")
print("=" * 60)

print("Expected : ", expected)
print("Predicted: ", prediction)

# Normalize text for comparison
def normalize(text):
    return " ".join(
        text.lower()
        .replace("'", "")
        .split()
    )

if normalize(prediction) == normalize(expected):
    print("\n✅ Prediction matches the training transcription!")
else:
    print("\n⚠️ Prediction differs from the training transcription.")

print("=" * 60)

============================================================
🎤 FINE-TUNED MMS ENGLISH ASR TEST
============================================================
Expected :  It's wake up time
Predicted:  aini dhb

⚠️ Prediction differs from the training transcription.
============================================================